### ISSUE TITLE
improve progress tracking

### ISSUE THREAD

**Issue by othiym23** [othiym23/packard#23]
`packard unpack` works nearly perfectly right now. A few things might make it easy to replicate that experience across packard:
- [ ] commands should only have an abstract interface for attaching a progress stream or marking work complete to a single object. The current pattern of looking up a progress group from a map breaks data hiding in a way that makes it very difficult to maintain.
- [ ] the progress group for a given file should be created at the beginning of the process, e.g. `packard unpack` would create a progress group for each archive file it's processing, which would in turn have progress groups for each entry in the archive, which would have one progress tracker each for extracting, scanning for tags, and moving into place.
- [ ] as much as possible, the code that knows about progress groups should be self-contained
